"""added datetime to posts table

Revision ID: 24691002d46e
Revises: 2336d29f0d02
Create Date: 2024-02-13 16:56:06.858589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24691002d46e'
down_revision: Union[str, None] = '2336d29f0d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('datetime', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'datetime')
    # ### end Alembic commands ###
