"""changed time to datetime in pokes table

Revision ID: aae66fab9c86
Revises: 45fc3ab77c16
Create Date: 2024-02-16 14:48:35.029730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aae66fab9c86'
down_revision: Union[str, None] = '45fc3ab77c16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokes', sa.Column('datetime', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False))
    op.drop_column('pokes', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokes', sa.Column('time', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False))
    op.drop_column('pokes', 'datetime')
    # ### end Alembic commands ###
